# Generated by Django 5.2.7 on 2026-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_action_history_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='desired_attribute_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
