# Generated by Django 5.2.5 on 2026-03-26 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.CharField(help_text='Structured goal description. Not a raw transcript.', max_length=500)),
                ('app_package', models.CharField(db_index=True, max_length=255)),
                ('steps', models.JSONField(help_text='Ordered list of ActionStep dicts.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('executing', 'Executing'), ('completed', 'Completed'), ('aborted', 'Aborted')], db_index=True, default='draft', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='agent_sessions.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_transcript', models.TextField()),
                ('parsed_intent', models.JSONField(default=dict, help_text="Structured intent extracted by LLM. Example: {app: 'WhatsApp', action: 'send_message', recipient: 'Alice', text: '...'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='agent_sessions.agentsession')),
            ],
        ),
    ]
