# Generated by Django 5.2.5 on 2026-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentrecord',
            name='ambiguity_flags',
            field=models.JSONField(default=list, help_text='List of ambiguity descriptions reported by the LLM.'),
        ),
        migrations.AddField(
            model_name='intentrecord',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='LLM-reported confidence score 0–1. Below 0.5 flags ambiguity.'),
        ),
        migrations.AddField(
            model_name='intentrecord',
            name='goal_type',
            field=models.CharField(blank=True, default='', help_text='Classified goal type: send_message, open_app, navigate_to, etc.', max_length=64),
        ),
        migrations.AddField(
            model_name='intentrecord',
            name='llm_raw_response',
            field=models.TextField(blank=True, default='', help_text='Raw JSON string returned by the LLM before parsing.'),
        ),
    ]
