# Generated by Django 5.2.5 on 2026-03-26 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAutomationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('allowed_packages', models.JSONField(default=list, help_text='Exhaustive allowlist of Android packages. Empty = deny all.')),
                ('blocked_action_types', models.JSONField(default=list, help_text='ActionType values the policy unconditionally rejects.')),
                ('always_confirm_action_types', models.JSONField(default=list, help_text='ActionType values that always require a confirmation step.')),
                ('max_steps_per_plan', models.PositiveIntegerField(default=30)),
                ('sensitive_screen_policy', models.CharField(choices=[('abort', 'abort'), ('pause', 'pause')], default='abort', max_length=16)),
                ('risk_threshold', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=16)),
                ('allow_coordinates_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'org_id'), name='unique_policy_per_user_org')],
            },
        ),
    ]
