# Generated by Django 5.2.5 on 2026-03-26 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_policy', '0001_initial'),
        ('agent_sessions', '0002_agentsession_input_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_packages', models.JSONField(default=list, help_text='System-level package allowlist. Overrides the hardcoded ALLOWED_PACKAGES.')),
                ('blocked_goals', models.JSONField(default=list, help_text='goal_type values that are unconditionally blocked.')),
                ('blocked_keywords', models.JSONField(default=list, help_text='Substrings that if found in any action param immediately block the plan.')),
                ('max_plan_length', models.PositiveIntegerField(default=20, help_text='Hard cap on the number of steps. Plans exceeding this are blocked.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'System Policy Config',
            },
        ),
        migrations.AddField(
            model_name='userautomationpolicy',
            name='allow_send_actions',
            field=models.BooleanField(default=True, help_text="If False, plans whose goal contains 'send' (messages, email) are blocked entirely."),
        ),
        migrations.AddField(
            model_name='userautomationpolicy',
            name='allow_text_entry',
            field=models.BooleanField(default=True, help_text='If False, any TYPE_TEXT step will be blocked.'),
        ),
        migrations.AddField(
            model_name='userautomationpolicy',
            name='blocked_keywords',
            field=models.JSONField(default=list, help_text='Additional user-specific blocked keywords (merged with system list). If found in any action param, the plan is blocked.'),
        ),
        migrations.AddField(
            model_name='userautomationpolicy',
            name='require_hard_confirmation_for_send',
            field=models.BooleanField(default=False, help_text='If True, REQUEST_CONFIRMATION steps preceding send/submit actions are marked hard_confirmation=true so the UI shows a stricter dialog.'),
        ),
        migrations.AlterField(
            model_name='userautomationpolicy',
            name='allowed_packages',
            field=models.JSONField(default=list, help_text='User-specific allowlist. Empty = use system defaults. Intersected with system ALLOWED_PACKAGES — cannot expand it.'),
        ),
        migrations.CreateModel(
            name='PolicyDecisionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.CharField(blank=True, default='', help_text='UUID of the ActionPlanRecord being evaluated.', max_length=64)),
                ('rule_name', models.CharField(db_index=True, max_length=128)),
                ('action_id', models.CharField(blank=True, default='', help_text='Step id if this decision applies to a specific action; empty for plan-level rules.', max_length=128)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('confirm', 'Confirm (inserted REQUEST_CONFIRMATION)'), ('block', 'Block')], db_index=True, max_length=16)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_decisions', to='agent_sessions.agentsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'plan_id'], name='agent_polic_session_08e262_idx')],
            },
        ),
    ]
