# Generated by Django 6.0.3 on 2026-03-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('feature_vector', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SocialEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gat_weight', models.FloatField(default=0.5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('elder_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_a', to='recommendations.elderprofile')),
                ('elder_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_b', to='recommendations.elderprofile')),
            ],
            options={
                'ordering': ['-gat_weight'],
                'unique_together': {('elder_a', 'elder_b')},
            },
        ),
    ]
