# Generated by Django 6.0.3 on 2026-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='baseline', max_length=32)),
                ('model_family', models.CharField(default='legacy_gat', max_length=64)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('confidence', models.CharField(default='high', max_length=16)),
                ('promotion_status', models.CharField(default='kept_candidate', max_length=32)),
                ('promoted', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='adapted_feature_vector',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='base_feature_vector',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='extraction_evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='extraction_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='feature_confidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='feature_vector_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='manual_overrides',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='vector_source',
            field=models.CharField(default='description_hybrid', max_length=64),
        ),
    ]
