# Generated by Django 5.2.5 on 2026-03-26 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceScreenState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(blank=True, db_index=True, default='', help_text='ActionStep.id that triggered this capture, if any.', max_length=64)),
                ('foreground_package', models.CharField(db_index=True, max_length=255)),
                ('window_title', models.CharField(blank=True, default='', max_length=512)),
                ('screen_hash', models.CharField(db_index=True, help_text='Deterministic hash of the accessibility node tree.', max_length=128)),
                ('focused_element_ref', models.CharField(blank=True, default='', max_length=255)),
                ('is_sensitive', models.BooleanField(db_index=True, default=False, help_text='If True, nodes are redacted and execution is halted.')),
                ('nodes', models.JSONField(default=list, help_text='Flat list of AccessibilityNode dicts. Empty when is_sensitive=True.')),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_states', to='agent_sessions.agentsession')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentActionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.UUIDField(db_index=True)),
                ('step_id', models.CharField(db_index=True, max_length=64)),
                ('step_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('success', 'success'), ('failure', 'failure'), ('timeout', 'timeout'), ('aborted', 'aborted'), ('skipped', 'skipped')], db_index=True, max_length=16)),
                ('error_code', models.CharField(blank=True, choices=[('', ''), ('ELEMENT_NOT_FOUND', 'ELEMENT_NOT_FOUND'), ('ELEMENT_NOT_CLICKABLE', 'ELEMENT_NOT_CLICKABLE'), ('APP_NOT_FOREGROUND', 'APP_NOT_FOREGROUND'), ('SCREEN_MISMATCH', 'SCREEN_MISMATCH'), ('TIMEOUT', 'TIMEOUT'), ('SENSITIVE_SCREEN', 'SENSITIVE_SCREEN'), ('CONFIRMATION_REJECTED', 'CONFIRMATION_REJECTED'), ('POLICY_VIOLATION', 'POLICY_VIOLATION'), ('UNKNOWN', 'UNKNOWN')], default='', max_length=32)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('executed_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_events', to='agent_sessions.agentsession')),
                ('screen_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_events', to='device_bridge.devicescreenstate')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
