# Generated by Django 6.0.3 on 2026-03-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprofile_accounttoken_importedcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('profile_viewed', 'Profile Viewed'), ('recommendation_clicked', 'Recommendation Clicked'), ('search_result_opened', 'Search Result Opened'), ('description_query_submitted', 'Description Query Submitted'), ('friend_request_sent', 'Friend Request Sent'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_declined', 'Friend Request Declined'), ('friend_request_canceled', 'Friend Request Canceled'), ('contact_match_hit', 'Contact Match Hit'), ('call_tapped', 'Call Tapped'), ('email_tapped', 'Email Tapped')], max_length=48)),
                ('discovery_mode', models.CharField(choices=[('for_you', 'For You'), ('describe_someone', 'Describe Someone'), ('search', 'Search'), ('direct', 'Direct')], default='direct', max_length=32)),
                ('query_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('signal_strength', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_activities', to='accounts.accountprofile')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_recommendation_activities', to='accounts.accountprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
