# Generated by Django 6.0.3 on 2026-03-27 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountprofile_dynamic_profile_summary_and_profile_notes'),
        ('recommendations', '0003_elderprofile_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='microphone_permission_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='phone_permission_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='phone_permission_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='voice_navigation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='accountprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_phone_number', ''), _negated=True), fields=('normalized_phone_number',), name='unique_account_profile_normalized_phone_number'),
        ),
    ]
