# Generated by Django 6.0.3 on 2026-03-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountprofile_dynamic_profile_summary_and_profile_notes'),
        ('accounts', '0005_cleanup_orphan_recommendationactivity'),
    ]

    operations = [
    ]
