# Generated by Django 6.0.3 on 2026-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountprofile_microphone_permission_granted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('normalized_phone_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('dynamic_profile_summary', models.TextField(blank=True)),
                ('conversation_history', models.JSONField(blank=True, default=list)),
                ('current_mode', models.CharField(choices=[('collecting', 'Collecting'), ('login_confirmation', 'Login Confirmation'), ('ready_to_register', 'Ready To Register'), ('completed', 'Completed')], default='collecting', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
