# Generated by Django 5.2.5 on 2026-03-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260327_1405'),
        ('accounts', '0006_onboardingdraft'),
    ]

    operations = [
    ]
