# Generated by Django 5.2.5 on 2026-03-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0006_merge_20260327_1405_0006_onboardingdraft'),
        ('accounts', '0007_merge_20260327_2045'),
    ]

    operations = [
    ]
