# Generated by Codex on 2026-03-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20260327_2131"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="whiteboard_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ConnectionThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_connection_threads",
                        to="accounts.accountprofile",
                    ),
                ),
                (
                    "participant_high",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_threads_high",
                        to="accounts.accountprofile",
                    ),
                ),
                (
                    "participant_low",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_threads_low",
                        to="accounts.accountprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_connection_messages",
                        to="accounts.accountprofile",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="accounts.connectionthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="connectionthread",
            constraint=models.UniqueConstraint(
                fields=("participant_low", "participant_high"),
                name="unique_connection_thread_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectionthread",
            constraint=models.CheckConstraint(
                condition=~models.Q(participant_low=models.F("participant_high")),
                name="connection_thread_not_to_self",
            ),
        ),
    ]
