# Generated by Django 5.2.5 on 2026-03-26 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('planning', 'Planning'), ('plan_ready', 'Plan Ready'), ('approved', 'Approved'), ('executing', 'Executing'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('paused', 'Paused'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('failed', 'Failed')], db_index=True, default='created', max_length=32)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField(help_text='Raw user input. Never copied into ActionPlan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.UUIDField(db_index=True)),
                ('step_id', models.CharField(max_length=64)),
                ('app_name', models.CharField(max_length=128)),
                ('app_package', models.CharField(max_length=255)),
                ('action_summary', models.TextField()),
                ('recipient', models.CharField(blank=True, default='', max_length=512)),
                ('content_preview', models.TextField(blank=True, default='')),
                ('sensitivity', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='agent_sessions.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
