# Generated by Django 5.2.5 on 2026-03-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='input_mode',
            field=models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='voice', max_length=16),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Last keep-alive ping from the Android device.', null=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='previous_status',
            field=models.CharField(blank=True, default='', help_text='Status snapshot before the session was paused, used for resume.', max_length=32),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='supported_packages',
            field=models.JSONField(default=list, help_text='Android packages the device reports as installed and supported.'),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='transcript',
            field=models.TextField(blank=True, default='', help_text='Raw user input. Never copied into ActionPlan.'),
        ),
    ]
