# Generated by Django 5.2.5 on 2026-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0002_agentsession_input_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='retry_counts',
            field=models.JSONField(default=dict, help_text="Per-action retry counters: {'action_id': n, '_screen_action_id': n}. Reset to {} when a new plan is compiled."),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of first EXECUTING transition — used for session-level timeout.', null=True),
        ),
    ]
