# Generated by Django 5.2.5 on 2026-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0003_agentsession_retry_counts_agentsession_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='step_history',
            field=models.JSONField(default=list, help_text='Ordered list of executed steps with results. Each entry: {step_index, action_type, params, reasoning, result_code, result_success, screen_hash_before, screen_hash_after, timestamp}. Never contains raw screenshots or sensitive field content.'),
        ),
    ]
