# Generated by Django 5.2.5 on 2026-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0004_add_step_history_to_agentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='entities',
            field=models.JSONField(blank=True, default=dict, help_text='Parsed intent entities: recipient, message, url, query, …'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='goal',
            field=models.TextField(blank=True, default='', help_text='Short structured goal description from intent parsing.'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='risk_level',
            field=models.CharField(blank=True, default='low', help_text='Risk level from intent parsing: low | medium | high.', max_length=16),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='target_app',
            field=models.CharField(blank=True, default='', help_text='Target Android package name (e.g. com.whatsapp).', max_length=255),
        ),
    ]
