# Generated by Django 6.0.3 on 2026-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_sessions", "0006_add_reasoning_provider_to_agentsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsession",
            name="pending_user_input",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Clarification gate state for a pending user-input query. "
                    "Shape: {query_id, status, question, attempt_count, max_attempts, "
                    "required_fields, candidates, ui_context, reason, last_user_reply, "
                    "followup_question, why_unresolved, fallback_mode, entity_updates}."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="agentsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("planning", "Planning"),
                    ("plan_ready", "Plan Ready"),
                    ("approved", "Approved"),
                    ("executing", "Executing"),
                    ("awaiting_confirmation", "Awaiting Confirmation"),
                    ("awaiting_user_input", "Awaiting User Input"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("aborted", "Aborted"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="created",
                max_length=32,
            ),
        ),
    ]
