# Generated by Django 5.2.5 on 2026-03-26 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('session_created', 'Session Created'), ('intent_stored', 'Intent Stored'), ('plan_compiled', 'Plan Compiled'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('step_dispatched', 'Step Dispatched'), ('step_succeeded', 'Step Succeeded'), ('step_failed', 'Step Failed'), ('confirmation_requested', 'Confirmation Requested'), ('confirmation_approved', 'Confirmation Approved'), ('confirmation_rejected', 'Confirmation Rejected'), ('sensitive_screen_detected', 'Sensitive Screen Detected'), ('session_paused', 'Session Paused'), ('session_aborted', 'Session Aborted'), ('session_completed', 'Session Completed'), ('policy_violation', 'Policy Violation')], db_index=True, max_length=64)),
                ('actor', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('android', 'Android')], default='system', max_length=16)),
                ('payload', models.JSONField(default=dict, help_text='Structured event data. Raw screenshots and sensitive values are never stored.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='agent_sessions.agentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
