# Generated by Django 6.0.3 on 2026-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_log", "0004_alter_auditrecord_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditrecord",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("session_created", "Session Created"),
                    ("intent_stored", "Intent Stored"),
                    ("plan_compiled", "Plan Compiled"),
                    ("plan_approved", "Plan Approved"),
                    ("plan_rejected", "Plan Rejected"),
                    ("step_dispatched", "Step Dispatched"),
                    ("step_succeeded", "Step Succeeded"),
                    ("step_failed", "Step Failed"),
                    ("confirmation_requested", "Confirmation Requested"),
                    ("confirmation_approved", "Confirmation Approved"),
                    ("confirmation_rejected", "Confirmation Rejected"),
                    ("user_input_requested", "User Input Requested"),
                    ("user_input_received", "User Input Received"),
                    ("user_input_resolved", "User Input Resolved"),
                    ("user_input_fallback", "User Input Fallback"),
                    ("sensitive_screen_detected", "Sensitive Screen Detected"),
                    ("session_paused", "Session Paused"),
                    ("session_resumed", "Session Resumed"),
                    ("session_cancelled", "Session Cancelled"),
                    ("session_aborted", "Session Aborted"),
                    ("session_completed", "Session Completed"),
                    ("policy_violation", "Policy Violation"),
                    ("policy_enforced", "Policy Enforced"),
                    ("plan_blocked", "Plan Blocked by Policy"),
                    ("llm_step_reasoned", "LLM Step Reasoned"),
                    ("llm_validation_error", "LLM Response Validation Error"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
