# Generated by Django 5.2.7 on 2026-03-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='history_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='actionattributescore',
            name='history_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mainuserprofile',
            name='state_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='useractionedge',
            name='signal_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userattributescore',
            name='history_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
